# Collector specific configuration
base_url: "https://api.psdata.un.org/public/"

dataset_names:
  DPO-UCLATEST: "peacekeeping-uniformed-contributions-by-rank-of-tcc-pcc"
  DPO-UCHISTORICAL: "peacekeeping-uniformed-contributions-by-gender"
  DPPADPOSS-FATALITIES: "peacekeeping-fatalities"
  DPPADPOSS-PKO: "peacekeeping-core-dataset-active-missions"

allowed_tags:
  - "complex emergency-conflict-security"
  - "environment"
  - "fatalities"
  - "gender"
  - "logistics"
  - "military"
  - "peacekeeping"
